# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=16, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=60, verbose_name='\u5bc6\u7801')),
                ('phoneNumber', models.CharField(max_length=13, verbose_name='\u7535\u8bdd')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shopid', models.AutoField(primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=32, verbose_name='\u5e97\u540d')),
                ('bossName', models.CharField(max_length=32, verbose_name='\u8001\u677f\u540d\u5b57')),
                ('shopImage', models.ImageField(upload_to='image/shop')),
            ],
        ),
    ]
