# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuId', models.AutoField(primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=40, verbose_name='\u83dc\u540d')),
                ('price', models.FloatField(default=0.0, verbose_name='\u4ef7\u683c')),
                ('shopImage', models.ImageField(upload_to='image/menu', verbose_name='\u7167\u7247')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 5, 12, 6, 17, 218903, tzinfo=utc), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopImage',
            field=models.ImageField(upload_to='image/shop', verbose_name='\u7167\u7247'),
        ),
        migrations.AddField(
            model_name='menu',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Shop'),
        ),
    ]
