# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160305_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phoneNumber',
            field=models.CharField(default=datetime.datetime(2016, 3, 5, 12, 11, 3, 334278, tzinfo=utc), max_length=40, verbose_name='\u7535\u8bdd'),
            preserve_default=False,
        ),
    ]
