# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shop_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='shopImage',
            new_name='menuImage',
        ),
        migrations.AddField(
            model_name='menu',
            name='menuStatus',
            field=models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u4e0b\u67b6')], default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='\u7eac\u5ea6'),
        ),
        migrations.AddField(
            model_name='shop',
            name='lontitude',
            field=models.FloatField(default=0, verbose_name='\u7ecf\u5ea6'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shopStatus',
            field=models.IntegerField(choices=[(1, '\u6b63\u5e38\u8425\u4e1a'), (2, '\u7981\u6b62\u8425\u4e1a')], default=2, verbose_name='\u72b6\u6001'),
        ),
    ]
