# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shop_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=32)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('orderStatus', models.IntegerField(choices=[(1, '\u5df2\u4e0b\u5355'), (2, '\u5df2\u63a5\u5355'), (3, '\u5df2\u7ecf\u9001\u51fa'), (4, '\u5df2\u7ecf\u5b8c\u6210')], default=1, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('menues', models.ManyToManyField(to='api.Menu')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Shop')),
            ],
        ),
    ]
