# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_otoorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(primary_key=True, serialize=False)),
                ('addressName', models.CharField(max_length=200, verbose_name='\u5730\u5740')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='realName',
            field=models.CharField(default='', max_length=60, verbose_name='\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
    ]
