# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160306_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='otoorder',
            name='favourable',
            field=models.FloatField(default=0, verbose_name='\u4f18\u60e0\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='otoorder',
            name='price',
            field=models.FloatField(default=0, verbose_name='\u603b\u4ef7'),
        ),
        migrations.AddField(
            model_name='shop',
            name='limitAmount',
            field=models.FloatField(default=20, verbose_name='\u6700\u5c0f\u91d1\u989d\u8d77\u9001'),
        ),
        migrations.AddField(
            model_name='shop',
            name='maxAmount',
            field=models.FloatField(default=0, verbose_name='\u6ee1\u51cf\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='shop',
            name='subtrackPrice',
            field=models.FloatField(default=0, verbose_name='\u51cf\u53bb\u91d1\u989d'),
        ),
    ]
