# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160306_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='userType',
            field=models.IntegerField(default=1, verbose_name='\u7528\u6237\u7c7b\u578b'),
        ),
    ]
