# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_person_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='person',
            name='realName',
        ),
        migrations.AddField(
            model_name='address',
            name='phoneNumber',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='address',
            name='userName',
            field=models.CharField(default='', max_length=14),
        ),
    ]
