# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160311_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='status',
            field=models.IntegerField(choices=[(1, '\u9ed8\u8ba4\u5730\u5740'), (2, '\u5e38\u7528\u5730\u5740')], default=2, verbose_name='\u5730\u5740\u72b6\u6001'),
        ),
    ]
