# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_address_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otoorder',
            old_name='orderId',
            new_name='orderNumber',
        ),
        migrations.RemoveField(
            model_name='otoorder',
            name='id',
        ),
        migrations.AddField(
            model_name='otoorder',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Address'),
        ),
        migrations.AddField(
            model_name='otoorder',
            name='orderid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
