# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160317_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detailid', models.AutoField(primary_key=True, serialize=False)),
                ('menuName', models.CharField(default='', max_length=40, verbose_name='\u83dc\u5355\u540d\u5b57')),
                ('menuPrice', models.FloatField(default=0, verbose_name='\u83dc\u5355\u4ef7\u683c')),
            ],
        ),
        migrations.RemoveField(
            model_name='otoorder',
            name='menues',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OtoOrder'),
        ),
    ]
