# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160318_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='menuPrice',
            new_name='price',
        ),
    ]
