# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-19 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160318_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otoorder',
            name='person',
        ),
        migrations.RemoveField(
            model_name='otoorder',
            name='shop',
        ),
        migrations.AddField(
            model_name='otoorder',
            name='personName',
            field=models.CharField(default='', max_length=32, verbose_name='\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='otoorder',
            name='phoneNumber',
            field=models.CharField(default='', max_length=32, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='otoorder',
            name='shopName',
            field=models.CharField(default='', max_length=32, verbose_name='\u5546\u5e97\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='otoorder',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='\u5730\u5740'),
        ),
    ]
