# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-19 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160319_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='otoorder',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
    ]
